
import logo.*;
import simplerjogl.shell.*;

/**
 * An application that runs our Logo-style drawing environment.
 * 
 * @author Seth Battis
 * @version 1.0
 */
public class LogoApp
{
	public static void main (String[] args)
	{
		/* instantiate a new Logo renderer from the LogoScript extension */
		LogoRenderer renderer = new LogoScript ();

		/* open a new window to contain the application */
		ShellFrame frame = ShellFrame.createFrame ("Logo", false);

		/*
		 * bind the OpenGL events to the Logo renderer's event handlers
		 * (based on SimplerJOGL)
		 */
		frame.addGLEventListener (renderer);

		/*
		 * bind the events generated by the SimplerJOGL shell to the Logo
		 * renderer
		 */
		frame.addShellListener (renderer);

		/* start it all up! */
		frame.start ();
	}
}